Assignment features
houseofgeeks/hgv2 pull request #83
Opened 2024-04-14 09:13 UTC by irfan-iiitr

**Tasks Done**
1. Get assignments by LevelID
2. Endpoints for project submission
3.  Verify submission

2024-04-14 12:28 UTC, irfan-iiitr commented
@aialok Please review this.

2024-05-29 07:47 UTC, aialok commented on src/controllers/assignment.controller.ts
>    }
LGTM

2024-05-29 07:47 UTC, aialok commented on src/repositories/assignment.repository.ts
> +import { level } from "winston";
LGTM

2024-05-29 07:47 UTC, aialok requested changes
LGTM

2024-05-29 07:48 UTC, merged